version: '3.7'

services:
  mysql:
    container_name: mysql_arquivei
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoice 
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './invoice/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - './invoice:/usr/src/app'
    user: 1000:1000
